### ISSUE TITLE
Currently all prs are made against the community branch (what about the editor branch)

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds-community/mirror-bot#3]
The community branch represents the upstreams master branch. But if there is a upstream pr against another branch the mirror bot also prs it against the community branch. That is wrong.

I would consider the editor branch out of scope. The mirror bot should ignore all prs that are on other branches than master.

See https://github.com/teeworlds/teeworlds/pull/2602

**Comment by ChillerDragon** [comment]
Why did https://github.com/teeworlds-community/teeworlds/pull/92 get mirrored?

**Comment by Bamcane** [comment]
> Why did [teeworlds-community/teeworlds#92](https://github.com/teeworlds-community/teeworlds/pull/92) get mirrored?
> 
> 为什么[teeworlds-community/teeworlds#92](https://github.com/teeworlds-community/teeworlds/pull/92)得到镜像？

I cloesed #91, it's a wrong mirror too
